import Link from "next/link";
import { ArrowRight, ShieldCheck } from "lucide-react";
import { Nav } from "@/components/nav";
import { Footer } from "@/components/footer";

const fit = [
  ["Hungry, not reckless", "You want more from the business, but you are not interested in growth that weakens what has already been built."],
  ["Established, not satisfied", "There is a real foundation worth building on—and enough ambition to question whether it can become more."],
  ["Truth over comfort", "Leadership is willing to examine uncomfortable realities without needing every answer to be flattering."],
  ["People matter", "The workforce is more than payroll. Capability, development, leadership and opportunity matter."],
  ["Opportunity remains", "The business is leaving something on the table—capacity, profitability, leadership depth, market position or enterprise value."],
  ["Legacy matters", "You are interested in building something stronger than this quarter's revenue number."],
] as const;

export default function WhoWeWorkWithPage() {
  return <><Nav /><main>
    <section className="industrial-grid bg-[#151b21] py-24 text-white"><div className="section-shell max-w-6xl"><div className="eyebrow">Who We Work With</div><h1 className="mt-5 max-w-6xl font-display text-5xl font-bold uppercase leading-[.95] sm:text-7xl">We don't look for companies that need help.<br/><span className="text-[#c85a24]">We look for companies capable of becoming extraordinary.</span></h1><p className="mt-8 max-w-3xl text-xl leading-9 text-slate-300">Fit is defined less by revenue, employee count or trade than by the kind of business leadership is determined to build.</p></div></section>
    <section className="bg-[#f2efe8] py-24"><div className="section-shell"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{fit.map(([title,body])=><div key={title} className="bg-white p-8"><h2 className="font-display text-2xl font-bold uppercase">{title}</h2><p className="mt-4 leading-7 text-slate-600">{body}</p></div>)}</div></div></section>
    <section className="bg-white py-24"><div className="section-shell grid gap-12 lg:grid-cols-2"><div><div className="eyebrow">Who You Work With Matters, Too</div><h2 className="mt-4 font-display text-4xl font-bold uppercase">The principles behind The Trades Pipeline are not marketing language.</h2></div><div className="space-y-5 text-lg leading-8 text-slate-600"><p>My Christian faith shapes how I try to live and conduct business. I believe God comes first, family comes before business, integrity matters when no one is watching, and success should ultimately create something worth leaving behind.</p><p>I'm proud to be an American and proud to work with the people and businesses that build, repair, maintain and strengthen this country.</p><p className="font-semibold text-[#151b21]">You do not have to share my faith or every one of my beliefs to work with The Trades Pipeline. You should expect honesty, confidentiality, respect, accountability and a relationship in which doing what is right matters more than doing what is convenient.</p><Link href="/foundation" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#c85a24]">Explore our Foundation <ArrowRight className="h-4 w-4" /></Link></div></div></section>
    <section className="bg-[#1b232b] py-24 text-white"><div className="section-shell"><div className="eyebrow">Protected Partnerships</div><div className="mt-6 grid gap-8 lg:grid-cols-[1fr_.7fr]"><div><h2 className="font-display text-4xl font-bold uppercase sm:text-5xl">Selective by design.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-400">The Trades Pipeline is built around a deliberately small number of partnerships so we can know the businesses, protect trust and remain deeply involved in meaningful work.</p></div><div className="border border-white/10 p-8"><ShieldCheck className="h-9 w-9 text-[#c85a24]"/><div className="mt-5 font-display text-2xl font-bold uppercase">One partner per trade per protected geography.</div><p className="mt-4 leading-7 text-slate-400">Protection is based on meaningful service-territory overlap. It is not artificial scarcity. It is conflict protection.</p><div className="mt-5 font-display text-2xl font-bold uppercase">Maximum 25 active partnerships.</div></div></div></div></section>
    <section className="bg-[#c85a24] py-20 text-white"><div className="section-shell text-center"><h2 className="font-display text-4xl font-bold uppercase">Let's build what matters.</h2><p className="mt-4 text-white/80">No presentation. No predetermined answers. No sales pitch.</p><Link href="/conversation" className="mt-8 inline-flex items-center gap-2 bg-white px-7 py-4 text-xs font-bold uppercase tracking-wider text-[#151b21]">Begin an Executive Conversation <ArrowRight className="h-4 w-4" /></Link></div></section>
  </main><Footer /></>;
}
