import Link from "next/link";
import { ArrowRight, Star, BrickWall, BarChart3, Search, Users, ShieldCheck, Cross, Flag, Handshake, Target, LockKeyhole, MessageCircle, Compass, Settings } from "lucide-react";
import { Nav } from "@/components/nav";

const fits = [
  {Icon:Star,title:"Have Ambition Beyond Maintaining",copy:"You want to grow, compete and build something remarkable—not just stay busy."},
  {Icon:BrickWall,title:"Have a Foundation Worth Building On",copy:"You've built something real. You have people, systems and customers. Now you want more from it."},
  {Icon:BarChart3,title:"Leave Money on the Table",copy:"You see opportunity, but constraints—visible or hidden—are holding you back."},
  {Icon:Search,title:"Are Willing to Face the Truth",copy:"You value candor over comfort and are willing to look at what's working, and what isn't."},
  {Icon:Users,title:"Care About Your People",copy:"You know your team is the engine of your business. You want to build a place worth staying."},
  {Icon:ShieldCheck,title:"Think Long Term",copy:"You're not just building for next month—you're building a business with a future."},
];
const expectations = [
  [Target,"Focus on What Matters","We pursue the opportunities and solve the constraints that move your business forward."],
  [LockKeyhole,"Confidentiality Always","Your business stays your business."],
  [MessageCircle,"Direct & Respectful","We'll tell you what we see—clearly and respectfully."],
  [Compass,"No Predetermined Solutions","We listen first. We recommend second."],
  [Users,"Earned Partnership","We keep earning the relationship by continuing to create meaningful value."],
] as const;

export default function WhoWeWorkWithPage(){return <><Nav/><main className="bg-[#0b0f11] text-[#f2efe7]">
<section className="relative overflow-hidden border-b border-white/10"><div className="absolute inset-0 opacity-20" style={{backgroundImage:"linear-gradient(rgba(255,255,255,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.035) 1px,transparent 1px)",backgroundSize:"32px 32px"}}/><div className="relative mx-auto grid max-w-[1500px] lg:grid-cols-[39%_61%]"><div className="px-7 py-10 lg:px-12 lg:py-12"><h1 className="font-display text-[clamp(3.6rem,5.4vw,5.8rem)] font-bold uppercase leading-[.9]">Who We Work With</h1><h2 className="mt-6 font-display text-[clamp(1.8rem,2.2vw,2.6rem)] uppercase leading-[1.05] text-[#ef5b0a]">We Don't Look for Companies That Need Help.</h2><h3 className="mt-4 font-display text-[clamp(1.8rem,2.2vw,2.6rem)] uppercase leading-[1.05]">We Look for Companies Capable of Becoming Extraordinary.</h3><p className="mt-6 max-w-[520px] text-[15px] leading-7 text-white/82">We partner with hungry regional trade businesses—led by people who take pride in what they've built and are determined to build something even better.</p></div><div className="relative min-h-[430px] overflow-hidden lg:min-h-[520px]"><img src="/who-we-work-with-hero.png" alt="Trade business leaders collaborating around plans" className="absolute inset-0 h-full w-full object-cover object-center"/><div className="absolute inset-y-0 left-0 w-24 bg-gradient-to-r from-[#0b0f11] to-transparent lg:w-36"/></div></div></section>
<section className="border-b border-white/10 bg-[#0c1114]"><div className="mx-auto max-w-[1500px] px-7 py-8 lg:px-12"><div className="flex items-center gap-4"><div className="h-px flex-1 bg-[#a64216]"/><h2 className="font-display text-3xl uppercase">You Might Be a Great Fit If You...</h2><div className="h-px flex-1 bg-[#a64216]"/></div><div className="mt-7 grid md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{fits.map(({Icon,title,copy})=><div key={title} className="border-white/10 px-5 py-3 text-center xl:border-r last:border-r-0"><Icon className="mx-auto h-12 w-12 text-[#ef5b0a]"/><h3 className="mt-4 min-h-[58px] font-display text-lg uppercase leading-tight">{title}</h3><p className="mt-3 text-[12px] leading-5 text-white/70">{copy}</p></div>)}</div></div></section>
<section className="border-b border-white/10"><div className="mx-auto grid max-w-[1500px] lg:grid-cols-[43%_57%]"><div className="px-7 py-9 lg:px-12"><h2 className="font-display text-3xl uppercase">Who You Work With Matters, Too.</h2><div className="mt-3 h-[3px] w-12 bg-[#ef5b0a]"/><p className="mt-5 font-semibold">The principles behind The Trades Pipeline aren't marketing language.<br/>They're mine.</p><div className="mt-5 space-y-5 text-[13px] leading-5 text-white/78"><div className="flex gap-4"><Cross className="h-8 w-8 shrink-0 text-[#ef5b0a]"/><p>My Christian faith shapes how I try to live and conduct business. I believe God comes first, family comes before business, integrity matters when no one is watching, and success should ultimately create something worth leaving behind.</p></div><div className="flex gap-4"><Flag className="h-8 w-8 shrink-0 text-[#ef5b0a]"/><p>I'm proud to be an American and proud to work with the people and businesses that build, repair, maintain and strengthen this country.</p></div><div className="flex gap-4"><Handshake className="h-8 w-8 shrink-0 text-[#ef5b0a]"/><p>You don't have to share my faith or every one of my beliefs to work with The Trades Pipeline.</p></div><div className="flex gap-4"><ShieldCheck className="h-8 w-8 shrink-0 text-[#ef5b0a]"/><p>But you should expect honesty, confidentiality, respect, accountability—and a relationship in which doing what's right matters more than doing what's convenient.</p></div></div><p className="mt-6 font-display text-xl text-[#ef5b0a]">If those principles resonate with you,<br/>we'll probably have a lot to talk about.</p></div><div className="relative min-h-[470px] overflow-hidden bg-[#15100c]"><img src="/who-we-work-with-faith.png" alt="American flag, eagle and Bible representing faith, country and legacy" className="absolute inset-0 h-full w-full object-cover object-center"/><div className="absolute inset-y-0 left-0 w-16 bg-gradient-to-r from-[#0b0f11] to-transparent lg:w-24"/></div></div></section>
<section className="border-b border-white/10"><div className="mx-auto grid max-w-[1500px] lg:grid-cols-2"><div className="border-white/10 px-7 py-8 lg:border-r lg:px-12"><h2 className="font-display text-3xl uppercase">Protected Partnerships</h2><div className="mt-3 h-[3px] w-12 bg-[#ef5b0a]"/><div className="mt-6 grid gap-5 sm:grid-cols-[110px_1fr]"><div className="flex h-28 w-28 items-center justify-center rounded-full border-[9px] border-[#494a47] bg-[#17191a]"><LockKeyhole className="h-14 w-14 text-[#ef5b0a]"/></div><div><p className="text-[13px] leading-5 text-white/75">We believe the best work happens in true partnership. That's why we maintain boundaries that protect our partners and the value we create together.</p><ul className="mt-4 space-y-3 text-[13px] leading-5 text-white/80"><li>✓ One partner per trade per protected geography (defined by service-territory overlap).</li><li>✓ A limited number of active partnerships (maximum 25) allows us to stay deeply involved and intentionally selective.</li><li>✓ We protect our partners from direct competition so you can invest with confidence.</li></ul></div></div><p className="mt-5 text-[13px] font-semibold">Exclusivity isn't a marketing tactic. It's how we honor the trust placed in us—and the results we pursue.</p></div><div className="px-7 py-8 lg:px-12"><h2 className="font-display text-3xl uppercase">What You Can Expect From Us</h2><div className="mt-3 h-[3px] w-12 bg-[#ef5b0a]"/><div className="mt-5 border border-[#7d4b31]">{expectations.map(([Icon,title,copy])=><div key={title} className="grid grid-cols-[56px_175px_1fr] border-b border-[#7d4b31] last:border-b-0"><div className="flex items-center justify-center border-r border-[#7d4b31] p-3"><Icon className="h-6 w-6 text-[#ef5b0a]"/></div><div className="border-r border-[#7d4b31] p-3 font-display uppercase">{title}</div><div className="p-3 text-[12px] leading-5 text-white/75">{copy}</div></div>)}</div></div></div></section>
<section className="bg-[#f2eee6] text-[#111820]"><div className="mx-auto grid max-w-[1500px] lg:grid-cols-[1.3fr_.55fr_.55fr_.55fr]"><div className="px-7 py-7 lg:px-12"><h2 className="font-display text-4xl uppercase">Let's Build What Matters.</h2><p className="mt-3 max-w-[560px] text-[13px] leading-5">If you're committed to building a stronger business—one that creates opportunity, serves your people, and leaves a legacy you're proud of—let's start a conversation.</p><Link href="/conversation" className="mt-5 inline-flex items-center gap-5 bg-[#c94f0a] px-7 py-3 font-display uppercase text-white">Begin an Executive Conversation <ArrowRight className="h-4 w-4"/></Link><p className="mt-2 text-[11px]">No presentation. No predetermined answers. No sales pitch.</p></div>{[[Cross,"Faith","Our foundation.","It shapes how we live, lead and serve."],[Users,"Family","Our priority.","It keeps us grounded and grateful."],[Settings,"Business","Our calling.","It provides opportunity, freedom and impact."]].map(([Icon,title,a,b]:any)=><div key={title} className="border-t border-black/20 px-5 py-7 text-center lg:border-l lg:border-t-0"><Icon className="mx-auto h-12 w-12"/><h3 className="mt-3 font-display text-2xl uppercase">{title}</h3><p className="mt-2 text-[12px]">{a}<br/>{b}</p><Link href="/foundation" className="mt-4 inline-flex items-center gap-2 font-display text-[11px] uppercase text-[#c94f0a]">Explore Our Foundation <ArrowRight className="h-3 w-3"/></Link></div>)}</div></section>
<footer className="border-t border-white/10 bg-[#091015]"><div className="mx-auto grid max-w-[1500px] items-center gap-5 px-7 py-5 md:grid-cols-3 lg:px-12"><div className="flex items-center gap-4"><img src="/ttp-logo-site.png" className="h-12 w-auto" alt="The Trades Pipeline"/><p className="text-[11px] leading-4 text-white/70">Built to help extraordinary companies become even stronger—without breaking what matters most.</p></div><div className="text-center font-display text-xl uppercase">Truth Before Assumption.<br/><span className="text-[#ef5b0a]">Growth Without Breaking.</span></div><div className="flex items-center justify-end gap-4"><Flag className="h-10 w-10 text-[#ef5b0a]"/><p className="text-[11px] text-white/70">Proud to be American.<br/>Honored to serve.</p></div></div></footer>
</main></>}
