import Link from "next/link";
import { ArrowRight, Cross, Users, Settings, Star, Wrench, ShieldCheck, Flag, Check, Leaf } from "lucide-react";
import { Nav } from "@/components/nav";

const principles = [[ShieldCheck,"Truth before assumption."],[Check,"Promises before convenience."],[Users,"People before process."],[Leaf,"Stewardship before excess."],[Star,"Legacy beyond revenue."]] as const;

export default function FoundationPage(){return <><Nav/><main className="bg-[#0d1113] text-[#f3efe7] overflow-x-hidden">
<section className="bg-[#0a0d0f]"><div className="mx-auto max-w-[1500px]"><img src="/foundation-hero.png" alt="Foundation — faith, integrity, people and legacy" className="block h-auto w-full"/></div></section>
<section className="border-y border-white/10 bg-[#111619]"><div className="mx-auto max-w-[1500px] px-5 py-7 sm:px-7 lg:px-12"><div className="text-center"><div className="mx-auto mb-4 flex items-center gap-4"><div className="hidden h-px flex-1 bg-[#9b3e16] sm:block"/><h2 className="font-display text-[clamp(1.55rem,2.6vw,2.8rem)] uppercase leading-tight">What We Build Should Serve What Matters Most.</h2><div className="hidden h-px flex-1 bg-[#9b3e16] sm:block"/></div>
<div className="hidden font-display text-[clamp(3rem,5.4vw,5.3rem)] uppercase leading-none tracking-tight sm:flex sm:items-center sm:justify-center sm:gap-5"><span className="text-[#5f9ec6]">God</span><span className="text-[#ef5b0a]">→</span><span className="text-[#f1e6d7]">Family</span><span className="text-[#ef5b0a]">→</span><span className="text-[#c72f24]">Business</span></div>
<div className="mx-auto flex max-w-[280px] flex-col items-center font-display uppercase sm:hidden"><span className="text-5xl leading-none text-[#5f9ec6]">God</span><span className="my-1 text-3xl leading-none text-[#ef5b0a]">↓</span><span className="text-5xl leading-none text-[#f1e6d7]">Family</span><span className="my-1 text-3xl leading-none text-[#ef5b0a]">↓</span><span className="text-5xl leading-none text-[#c72f24]">Business</span></div></div>
<div className="mt-8 grid gap-8 lg:grid-cols-3 lg:gap-6"><div className="px-5 lg:border-r lg:border-white/10"><Cross className="mx-auto h-12 w-12 text-[#6fa5c3]"/><h3 className="mt-3 text-center font-display text-2xl uppercase text-[#6fa5c3]">God<br/><span className="text-lg">Our Foundation</span></h3><p className="mx-auto mt-3 max-w-[300px] text-center text-[13px] leading-6 text-white/75">Faith shapes how we live, how we lead, how we serve, and how we conduct ourselves—especially when nobody is watching.</p></div><div className="px-5 lg:border-r lg:border-white/10"><Users className="mx-auto h-12 w-12 text-[#efe0cd]"/><h3 className="mt-3 text-center font-display text-2xl uppercase">Family<br/><span className="text-lg">Our Priority</span></h3><p className="mx-auto mt-3 max-w-[300px] text-center text-[13px] leading-6 text-white/75">Business should create opportunity for the people we love, not consume the relationships we're building it for.</p></div><div className="px-5"><Settings className="mx-auto h-12 w-12 text-[#c72f24]"/><h3 className="mt-3 text-center font-display text-2xl uppercase text-[#c72f24]">Business<br/><span className="text-lg">Our Calling</span></h3><p className="mx-auto mt-3 max-w-[300px] text-center text-[13px] leading-6 text-white/75">Business creates livelihoods, opportunity, independence and impact. Done well, it becomes a vehicle for serving people and building something that lasts.</p></div></div></div></section>
<section className="border-b border-white/10 bg-[#0d1113]"><div className="mx-auto grid max-w-[1500px] lg:grid-cols-[32%_1fr_27%]"><div className="relative min-h-[390px] overflow-hidden"><img src="/foundation-legacy.png" alt="American builder and flag" className="absolute inset-0 h-full w-full object-cover object-center"/></div><div className="px-7 py-9 text-center lg:px-10"><p className="font-display text-xl uppercase tracking-wide text-[#ef5b0a]">Success Needs a Definition.</p><p className="mt-2 text-[13px] leading-5 text-white/75">Revenue matters. Profitability matters. Growth matters. Enterprise value matters.<br/>But none of them answers the final question:</p><h2 className="mt-5 font-display text-[clamp(3rem,4.3vw,5rem)] uppercase leading-[.92]">What Will You Be<br/>Remembered For?</h2><p className="mt-4 text-[13px] text-white/75">The businesses we build will eventually belong to someone else—or cease to exist.</p><p className="mt-2 font-display text-base text-[#ef5b0a]">The impact we have on people can outlast them.</p></div><div className="flex flex-col justify-center px-7 py-8 lg:px-8"><div className="space-y-6">{[[Star,"Build People","who build the future."],[Wrench,"Strengthen Communities","through meaningful work."],[ShieldCheck,"Create Opportunity","for the next generation."],[Flag,"Leave Something Better","than we found it."]].map(([Icon,a,b]:any)=><div key={a} className="flex gap-4"><Icon className="h-8 w-8 shrink-0 text-[#ef5b0a]"/><div><div className="font-display text-lg uppercase text-[#ef5b0a]">{a}</div><div className="text-[12px] text-white/75">{b}</div></div></div>)}</div></div></div></section>
<section className="border-b border-white/10 bg-[#0e1315]"><div className="mx-auto grid max-w-[1500px] lg:grid-cols-3"><div className="relative aspect-square overflow-hidden border-white/10 lg:aspect-[586/429] lg:border-r"><img src="/foundation-built.png" alt="Built in a country that still rewards builders" className="absolute inset-0 h-full w-full object-cover object-center"/></div><div className="relative aspect-square overflow-hidden border-white/10 lg:aspect-[586/429] lg:border-r"><img src="/foundation-integrity.png" alt="Integrity doesn't need an audience" className="absolute inset-0 h-full w-full object-cover object-center"/></div><div className="flex min-h-[360px] flex-col justify-center px-7 py-8 lg:aspect-[586/429] lg:min-h-0 lg:px-10"><h2 className="font-display text-3xl uppercase leading-tight">The Principles<br/>That Guide Us.</h2><div className="mt-4 h-[3px] w-12 bg-[#ef5b0a]"/><div className="mt-6 space-y-5">{principles.map(([Icon,t])=><div key={t} className="flex items-center gap-4"><Icon className="h-6 w-6 text-[#ef5b0a]"/><span className="text-[14px]">{t}</span></div>)}</div></div></div></section>
<section className="bg-[#eee6d8] text-[#17202a]"><div className="mx-auto grid max-w-[1500px] lg:grid-cols-[28%_44%_28%]"><div className="relative min-h-[300px] overflow-hidden"><img src="/foundation-eagle.png" alt="Bald eagle" className="absolute inset-0 h-full w-full object-cover object-center"/></div><div className="px-8 py-8 lg:px-10"><h2 className="font-display text-4xl uppercase">Our Foundation Is Ours.</h2><div className="mt-3 h-[3px] w-20 bg-[#8d2d1f]"/><p className="mt-5 text-[14px] leading-6">We don't expect every partner to share our faith, background or worldview.<br/>We do believe you deserve to know the principles guiding the people you're trusting with your business.</p><p className="mt-5 font-display text-lg uppercase text-[#a8271f]">Respect Doesn't Require Sameness.<br/>Trust Requires Honesty.</p></div><div className="relative min-h-[300px] overflow-hidden"><img src="/foundation-family.png" alt="Family walking toward an American industrial community" className="absolute inset-0 h-full w-full object-cover object-center"/></div></div></section>
<section className="bg-[#e9ddca]"><picture><source media="(min-width: 768px)" srcSet="/foundation-closing.png"/><img src="/foundation-closing-mobile.png" alt="What will you be remembered for? Build accordingly. The Trades Pipeline — Growth Without Breaking." className="block h-auto w-full"/></picture></section>
<section className="bg-[#0b0f11]"><div className="mx-auto flex max-w-[1500px] justify-center px-7 py-5"><Link href="/conversation" className="inline-flex items-center gap-4 bg-[#c94f0a] px-8 py-3 font-display uppercase text-white">Begin an Executive Conversation <ArrowRight className="h-4 w-4"/></Link></div></section>
</main></>}
