import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Nav } from "@/components/nav";
import { Footer } from "@/components/footer";

export default function FoundationPage() {
  return <><Nav /><main>
    <section className="industrial-grid bg-[#151b21] py-24 text-white"><div className="section-shell text-center"><div className="eyebrow">Foundation</div><h1 className="mx-auto mt-5 max-w-5xl font-display text-5xl font-bold uppercase sm:text-7xl">What we build should serve what matters most.</h1><div className="mt-10 font-display text-4xl font-bold uppercase tracking-wide sm:text-6xl">God <span className="text-[#c85a24]">→</span> Family <span className="text-[#c85a24]">→</span> Business</div></div></section>
    <section className="bg-[#f2efe8] py-24"><div className="section-shell grid gap-6 lg:grid-cols-3"><div className="bg-white p-8"><div className="eyebrow">God — Our Foundation</div><p className="mt-5 text-lg leading-8 text-slate-600">Faith shapes how we try to live, lead, serve and conduct ourselves—especially when nobody is watching.</p></div><div className="bg-white p-8"><div className="eyebrow">Family — Our Priority</div><p className="mt-5 text-lg leading-8 text-slate-600">Business should create opportunity for the people we love, not consume the relationships we are building it for.</p></div><div className="bg-white p-8"><div className="eyebrow">Business — Our Calling</div><p className="mt-5 text-lg leading-8 text-slate-600">Business creates livelihoods, opportunity, independence and impact. Done well, it becomes a vehicle for serving people and building something that lasts.</p></div></div></section>
    <section className="bg-white py-24"><div className="section-shell text-center"><div className="eyebrow">Success Needs a Definition</div><h2 className="mx-auto mt-5 max-w-4xl font-display text-5xl font-bold uppercase">What will you be remembered for?</h2><p className="mx-auto mt-7 max-w-3xl text-lg leading-8 text-slate-600">Revenue matters. Profitability matters. Growth matters. Enterprise value matters. But none of them answers the final question. Businesses may eventually belong to someone else—or cease to exist. The impact we have on people can outlast them.</p></div></section>
    <section className="bg-[#16202b] py-24 text-white"><div className="section-shell grid gap-12 lg:grid-cols-2"><div><div className="eyebrow">Built in America</div><h2 className="mt-4 font-display text-4xl font-bold uppercase sm:text-5xl">Built in a country that still rewards builders.</h2></div><div className="space-y-5 text-lg leading-8 text-slate-300"><p>We're proud to be American.</p><p>We're grateful to live in a country where someone can learn a trade, build a business, employ a community, create wealth for a family and leave the next generation something greater than they inherited.</p><p className="font-semibold text-white">We don't take that opportunity for granted.</p></div></div></section>
    <section className="bg-[#f2efe8] py-24"><div className="section-shell"><div className="eyebrow">Integrity</div><h2 className="mt-4 font-display text-4xl font-bold uppercase sm:text-5xl">Integrity doesn't need an audience.</h2><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-600">Character shows up when keeping our word costs something, when nobody would know otherwise, and when the right decision is not the most profitable one.</p><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{["Truth Before Assumption","Promises Before Convenience","People Before Process","Stewardship Before Excess","Legacy Beyond Revenue"].map(x=><div key={x} className="border border-slate-300 bg-white p-5 font-display text-lg font-bold uppercase">{x}</div>)}</div></div></section>
    <section className="bg-white py-24"><div className="section-shell text-center"><div className="eyebrow">Our Foundation Is Ours</div><h2 className="mx-auto mt-5 max-w-4xl font-display text-4xl font-bold uppercase">Respect doesn't require sameness. Trust requires honesty.</h2><p className="mx-auto mt-7 max-w-3xl text-lg leading-8 text-slate-600">We do not expect every partner to share our faith, background or worldview. We do believe you deserve to know the principles guiding the people you're trusting with your business.</p></div></section>
    <section className="bg-[#151b21] py-24 text-white"><div className="section-shell text-center"><h2 className="font-display text-5xl font-bold uppercase">What will you be remembered for?</h2><div className="mt-6 font-display text-4xl italic text-[#c85a24]">Build accordingly.</div><Link href="/" className="mt-10 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-400 hover:text-white">The Trades Pipeline <ArrowRight className="h-4 w-4" /></Link></div></section>
  </main><Footer /></>;
}
