import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Nav } from "@/components/nav";
import { Footer } from "@/components/footer";

export default function AboutPage() {
  return <><Nav /><main>
    <section className="industrial-grid bg-[#151b21] py-24 text-white"><div className="section-shell grid gap-12 lg:grid-cols-[1.1fr_.9fr]"><div><div className="eyebrow">About JL Davis</div><h1 className="mt-5 font-display text-5xl font-bold uppercase sm:text-7xl">Experience. Perspective. Purpose.</h1><p className="mt-8 max-w-3xl text-xl leading-9 text-slate-300">For more than 30 years, I've worked where business plans eventually have to become reality: inside the operation.</p></div><div className="border border-white/10 bg-white/[.03] p-8"><div className="text-sm font-bold uppercase tracking-[.2em] text-[#c85a24]">Truth Before Assumption</div><p className="mt-5 font-display text-3xl font-bold uppercase leading-tight">Business problems rarely stay in the department where they first appear.</p></div></div></section>
    <section className="bg-[#f2efe8] py-24"><div className="section-shell grid gap-12 lg:grid-cols-2"><div><div className="eyebrow">Experience Changes How You See a Business</div><h2 className="mt-4 font-display text-4xl font-bold uppercase">More than three decades of leadership under pressure.</h2></div><div className="space-y-5 text-lg leading-8 text-slate-600"><p>I've served as a Plant Manager, Store Manager and Supervisor across manufacturing, warehousing and retail—working behind the scenes where growth has to be supported by people, operations, systems, equipment and financial discipline.</p><p>I've experienced businesses growing. I've also experienced what happens when they aren't.</p><p className="font-semibold text-[#151b21]">The industries may change. The fundamentals of building an organization capable of performing under pressure often don't.</p></div></div></section>
    <section className="bg-white py-24"><div className="section-shell"><div className="eyebrow">You Know Your Trade</div><h2 className="mt-4 font-display text-4xl font-bold uppercase sm:text-5xl">I'm not here to teach it to you.</h2><div className="mt-8 max-w-4xl space-y-5 text-lg leading-8 text-slate-600"><p>A plumber knows plumbing better than I do. An electrician knows electrical work better than I do. An HVAC professional knows HVAC better than I do.</p><p className="font-semibold text-[#151b21]">They should.</p><p>My responsibility is different: ask better questions, see connections, challenge assumptions and help leadership determine what the business needs to support where they want to go.</p></div></div></section>
    <section className="bg-[#1b232b] py-24 text-white"><div className="section-shell grid gap-12 lg:grid-cols-2"><div><div className="eyebrow">Why The Trades Pipeline?</div><h2 className="mt-4 font-display text-4xl font-bold uppercase">A pipeline is only as strong as the system carrying the pressure.</h2></div><div className="space-y-5 text-lg leading-8 text-slate-400"><p>Increase demand beyond capacity and pressure rises. Restrict one point and the entire system behaves differently. Strengthen one component without understanding the others and you may simply move the constraint.</p><p className="font-semibold text-white">That's how we think about business.</p><div className="font-display text-3xl font-bold uppercase text-[#c85a24]">Growth Without Breaking.</div></div></div></section>
    <section className="bg-[#f2efe8] py-24"><div className="section-shell text-center"><div className="eyebrow">Humility Matters</div><h2 className="mt-5 font-display text-5xl font-bold uppercase">I don't have all the answers.</h2><p className="mx-auto mt-7 max-w-3xl text-lg leading-8 text-slate-600">And anyone who claims to understand your business before listening to you probably doesn't either. What I bring is a disciplined way of asking questions, examining connections, challenging assumptions and helping leadership get closer to the truth.</p></div></section>
    <section className="bg-white py-24"><div className="section-shell grid gap-12 lg:grid-cols-2"><div><div className="eyebrow">Beyond the Business</div><h2 className="mt-4 font-display text-4xl font-bold uppercase">Husband. Father. Christian. Proud American.</h2></div><div className="space-y-5 text-lg leading-8 text-slate-600"><p>Those roles matter more to me than any business title ever will. They're also part of why I believe businesses should create more than revenue—they should create freedom, opportunity, stronger families and something worth leaving behind.</p><Link href="/foundation" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#c85a24]">Explore our Foundation <ArrowRight className="h-4 w-4" /></Link></div></div></section>
    <section className="bg-[#c85a24] py-20 text-white"><div className="section-shell text-center"><h2 className="font-display text-4xl font-bold uppercase">I'm not asking you to trust a website.</h2><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-white/85">If something you've seen here causes you to look at your business differently, let's have a conversation. You can decide whether our way of thinking brings value to yours. And we'll do the same.</p><Link href="/conversation" className="mt-8 inline-flex items-center gap-2 bg-white px-7 py-4 text-xs font-bold uppercase tracking-wider text-[#151b21]">Begin an Executive Conversation <ArrowRight className="h-4 w-4" /></Link></div></section>
  </main><Footer /></>;
}
