import Link from "next/link";
import { ArrowRight, ShieldCheck, Users, Wrench, BarChart3, Search, MessageCircle, Activity, Target, TrendingUp } from "lucide-react";
import { Nav } from "@/components/nav";
import { Footer } from "@/components/footer";

const approach = [
  ["01", Search, "Understand", "Independent Executive Assessment", "We begin outside the business—studying what can be responsibly observed without assuming what cannot."],
  ["02", MessageCircle, "Discover", "Executive Growth Discovery", "Leadership gives us what public information cannot: context."],
  ["03", Activity, "Diagnose", "Internal Growth Intelligence", "The Nine Growth Gears are examined from inside the organization to identify pressure, capacity and interconnected constraints."],
  ["04", Target, "Prioritize", "Growth Synchronization™", "We determine what deserves attention first, what follows next, and what should deliberately wait."],
  ["05", TrendingUp, "Build", "Growth Partnership", "We work alongside leadership to strengthen the systems necessary to support sustainable growth."],
] as const;

export default function Home() {
  return <><Nav/><main className="bg-[#0d0f12]">
    <section className="relative overflow-hidden border-b border-white/10 bg-[#0d0f12] text-white"><div className="absolute inset-0 opacity-20" style={{backgroundImage:"linear-gradient(rgba(255,255,255,.025) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.02) 1px,transparent 1px)",backgroundSize:"38px 38px"}}/><div className="relative mx-auto grid max-w-[1500px] lg:grid-cols-[.74fr_1.26fr]"><div className="flex min-h-[620px] flex-col justify-center px-6 py-14 sm:px-10 lg:px-12 xl:px-14"><h1 className="font-display text-[clamp(4.4rem,7.2vw,7.8rem)] font-bold uppercase leading-[.79] tracking-[-.03em] text-[#f2f2ef]">Growth<br/><span className="text-[#ff6a00]">Without Breaking.</span></h1><div className="mt-6 h-1 w-28 bg-[#ff6a00]"/><p className="mt-6 font-display text-2xl uppercase leading-tight tracking-wide sm:text-3xl">Growth creates opportunity.<br/>It also creates pressure.</p><p className="mt-5 max-w-lg text-base leading-7 text-slate-300">The Trades Pipeline works with a small number of ambitious trade businesses to identify where growth is creating pressure—and help leadership build the capacity to support what comes next.</p><Link href="/approach" className="mt-8 inline-flex w-fit items-center gap-3 border border-[#ff6a00] px-6 py-4 font-display text-base font-bold uppercase tracking-[.08em] text-white transition hover:bg-[#ff6a00]">Explore Our Approach <ArrowRight className="h-5 w-5"/></Link><div className="mt-7 flex items-start gap-3 text-sm font-semibold uppercase tracking-[.08em] text-slate-200"><ShieldCheck className="mt-0.5 h-6 w-6 shrink-0 text-[#ff6a00]"/><span>One partnership per trade within<br className="hidden sm:block"/> overlapping service territories.</span></div></div><div className="relative min-h-[520px] overflow-hidden lg:min-h-[620px]"><img src="/hero-growth-system.jpg?v=20260816-2200" alt="Growth Synchronization pressure system illustrating The Nine Growth Gears" className="absolute inset-0 h-full w-full object-cover object-center"/><div className="absolute inset-y-0 left-0 w-20 bg-gradient-to-r from-[#0d0f12] to-transparent"/></div></div></section>
    <section className="bg-[#f3efe7] text-[#121417]"><div className="mx-auto grid max-w-[1500px] gap-8 px-6 py-8 sm:px-10 lg:grid-cols-[1.25fr_repeat(4,1fr)] lg:px-12 xl:px-14"><div><h2 className="font-display text-4xl font-bold uppercase tracking-tight">Growth Is a System.</h2><div className="mt-2 h-1 w-16 bg-[#ff6a00]"/><p className="mt-5 max-w-sm text-sm leading-6">More of one thing doesn't fix the wrong constraint.<br/>Sustainable growth happens when the business supporting the opportunity grows <span className="font-semibold underline decoration-[#ff6a00] decoration-2 underline-offset-4">with</span> it.</p></div>{[["More Leads","don't fix an operational bottleneck.",BarChart3],["More People","don't fix weak systems.",Users],["More Equipment","doesn't fix poor financial capacity.",Wrench],["More Revenue","doesn't automatically create a stronger business.",TrendingUp]].map(([t,b,I]:any)=><div key={t} className="border-black/15 text-center lg:border-l lg:pl-6"><I className="mx-auto h-10 w-10 text-[#ff6a00]"/><h3 className="mt-3 font-display text-lg font-bold uppercase">{t}</h3><p className="mx-auto mt-2 max-w-[170px] text-sm leading-6">{b}</p></div>)}</div></section>
    <section className="relative overflow-hidden border-y border-white/10 bg-[#111416] text-white"><div className="absolute inset-0 opacity-25" style={{backgroundImage:"linear-gradient(rgba(255,255,255,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.035) 1px,transparent 1px)",backgroundSize:"32px 32px"}}/><div className="relative mx-auto grid max-w-[1500px] items-center gap-8 px-6 py-8 sm:px-10 lg:grid-cols-[.7fr_1.3fr_.55fr] lg:px-12 xl:px-14"><div className="hidden h-28 rounded-full border border-white/10 opacity-50 lg:block" style={{background:"radial-gradient(circle,transparent 30%,rgba(255,255,255,.08) 31%,transparent 33%,rgba(255,255,255,.05) 34%,transparent 36%)"}}/><div><h2 className="font-display text-4xl font-bold uppercase">Growth Synchronization™</h2><p className="mt-2 font-display text-xl font-bold leading-tight text-[#ff6a00]">It's not about making each part better.<br/>It's about making the parts work better together.</p><p className="mt-4 max-w-2xl text-sm leading-6 text-slate-300">The strongest businesses aren't collections of strong departments. They're connected systems capable of supporting opportunity under pressure.</p></div><div className="font-display text-7xl tracking-[-.2em] text-[#ff6a00] opacity-80">›››››</div></div></section>
    <section className="bg-[#f3efe7] py-10 text-[#111416]"><div className="mx-auto max-w-[1500px] px-6 sm:px-10 lg:px-12 xl:px-14"><h2 className="font-display text-4xl font-bold uppercase">Our Approach</h2><div className="mt-2 h-1 w-16 bg-[#ff6a00]"/><div className="mt-8 grid gap-8 md:grid-cols-5">{approach.map(([n,I,t,s,b])=><div key={n}><div className="flex items-center gap-3"><span className="font-display text-3xl font-bold text-[#ff6a00]">{n}</span><I className="h-9 w-9"/></div><h3 className="mt-3 font-display text-xl font-bold uppercase">{t}</h3><p className="mt-1 font-display text-sm font-semibold leading-tight">{s}</p><p className="mt-3 text-sm leading-6 text-[#33383d]">{b}</p></div>)}</div></div></section>
    <section className="grid lg:grid-cols-[1fr_1fr_1.08fr]"><div className="bg-[#111416] p-8 text-white lg:p-10"><h2 className="font-display text-3xl font-bold uppercase">Who We Work With</h2><div className="mt-2 h-1 w-16 bg-[#ff6a00]"/><p className="mt-5 font-semibold leading-7">We don't look for companies that need help.<br/>We look for companies capable of becoming <span className="text-[#ff6a00]">extraordinary.</span></p><ul className="mt-5 space-y-2 text-sm text-slate-200">{["Established and past survival mode","Ambitious leadership with a growth mindset","Enough opportunity to make improvement meaningful","Willing to examine the business honestly","Complex enough that growth has consequences","Committed to building something lasting"].map(x=><li key={x} className="flex gap-2"><span className="text-[#ff6a00]">✓</span>{x}</li>)}</ul></div><div className="bg-[#181b1e] p-8 text-white lg:p-10"><h2 className="font-display text-3xl font-bold uppercase">What We Believe</h2><div className="mt-2 h-1 w-16 bg-[#ff6a00]"/><div className="mt-5 space-y-4">{[["Truth Before Assumption.","We don't prescribe before we understand."],["People Before Process.","Strong systems start with strong leadership."],["Growth With Responsibility.","Growth should strengthen the business and the people in it."],["Family Before Business.","Success is measured by what matters most."],["Legacy Beyond Revenue.","Build something you'll be proud to leave behind."]].map(([a,b])=><div key={a}><h3 className="font-display text-base font-bold uppercase text-[#ff6a00]">{a}</h3><p className="text-sm text-slate-300">{b}</p></div>)}</div></div><div className="bg-[#f3efe7] p-8 text-[#111416] lg:p-10"><h2 className="font-display text-3xl font-bold uppercase">Protected Partnerships</h2><div className="mt-2 h-1 w-16 bg-[#ff6a00]"/><div className="mt-6 flex gap-5"><ShieldCheck className="h-20 w-20 shrink-0 text-[#ff6a00]"/><div><p className="text-lg font-semibold leading-7">We don't help you grow while helping your direct competitor do the same.</p><p className="mt-3 text-sm leading-6">The Trades Pipeline maintains only one active partnership per trade within overlapping service territories.</p></div></div></div></section>
    <section className="border-t border-white/10 bg-[#0d0f12] text-white"><div className="mx-auto flex max-w-[1500px] flex-col gap-5 px-6 py-7 sm:px-10 lg:flex-row lg:items-center lg:justify-between lg:px-12 xl:px-14"><div><div className="font-display text-xl font-bold uppercase">No presentation. No predetermined answers.</div><p className="mt-1 text-sm text-slate-400">A first conversation is exactly that—a conversation.</p></div><Link href="/conversation" className="inline-flex items-center justify-center gap-3 bg-[#c94f0a] px-7 py-4 font-display text-lg font-bold uppercase text-white transition hover:bg-[#ff6a00]">Executive Conversation <ArrowRight className="h-5 w-5"/></Link><div className="font-display text-right text-lg uppercase tracking-wide">TheTradesPipeline.com<br/><span className="text-[#ff6a00]">Growth Without Breaking.</span></div></div></section>
  </main><Footer/></>;
}