import { ExternalLink } from "lucide-react";
import { Nav } from "@/components/nav";
import { Footer } from "@/components/footer";

const insights = [
  {cat:"Leadership",source:"Forbes",title:"Scaling Skilled Trades: Why Leadership Matters More Than Ever",url:"https://www.forbes.com/sites/danringo/2025/09/10/scaling-skilled-trades-why-leadership-matters-more-than-ever/",why:"Growth can create opportunity faster than it creates leadership capacity. The question is not simply whether a company can win more work. It is whether leadership can carry what comes next."},
  {cat:"People",source:"The Wall Street Journal",title:"The U.S. Needs Mechanics and Electricians. Big Business Is Spending to Create Some.",url:"https://www.wsj.com/business/autos/the-u-s-needs-mechanics-and-electricians-big-business-is-spending-to-create-some-7ea1f06c",why:"The workforce shortage is not only a hiring problem. It raises a harder question for established contractors: how intentionally are you building tomorrow's capability today?"},
  {cat:"Operations",source:"McKinsey & Company",title:"A New Operating Model for a New World",url:"https://www.mckinsey.com/capabilities/people-and-organizational-performance/our-insights/a-new-operating-model-for-a-new-world",why:"Opportunity and capability are not the same thing. Before asking how much a business can grow, leadership should understand what the organization is currently built to support."},
  {cat:"Systems",source:"Forbes",title:"A New AI Wave Is Supporting the Trades That Build Our World",url:"https://www.forbes.com/sites/joetoscano1/2026/06/18/a-new-ai-wave-is-supporting-the-trades-that-build-our-world/",why:"Technology creates leverage when it improves the system—not merely because it is new. The better question is where technology can meaningfully improve how work moves through the business."},
  {cat:"Market Pressure",source:"Construction Dive",title:"How Contractors Can Navigate Cost Pressures, Labor Shortages and Regulatory Hurdles in 2026",url:"https://www.constructiondive.com/news/construction-cost-labor-regulations-2026/808629/",why:"Pressure rarely arrives one Gear at a time. Leadership decisions become more important when workforce, cost, capacity and opportunity move simultaneously."},
  {cat:"Financial Capacity",source:"Construction Dive",title:"Turner's Cost Benchmark Surged 5.2% in Q2",url:"https://www.constructiondive.com/news/turners-building-cost-index-q2-2026/826514/",why:"Rising labor and material costs do more than change estimates. They test pricing discipline, working capital, project selection and the resilience of the organization carrying the work."},
] as const;

const filters=["All","People","Sales","Operations","Financial Capacity","Safety","Systems","Inventory","Facilities","Equipment"];

export default function InsightsPage(){return <><Nav/><main>
  <section className="industrial-grid bg-[#151b21] py-24 text-white"><div className="section-shell"><div className="eyebrow">Insights</div><h1 className="mt-5 max-w-5xl font-display text-5xl font-bold uppercase sm:text-7xl">What we're reading. What we're watching. Why it matters.</h1><p className="mt-8 max-w-3xl text-xl leading-9 text-slate-300">Growth pressure can involve workforce, leadership, technology, capital, operations, markets and customers at the same time. We surface the ideas we believe deserve an executive's attention.</p></div></section>
  <section className="border-b border-slate-200 bg-white py-6"><div className="section-shell flex flex-wrap gap-2">{filters.map(x=><span key={x} className={`px-4 py-2 text-[11px] font-bold uppercase tracking-wider ${x==="All"?"bg-[#151b21] text-white":"border border-slate-200 text-slate-500"}`}>{x}</span>)}</div></section>
  <section className="bg-[#f2efe8] py-24"><div className="section-shell grid gap-6 md:grid-cols-2 lg:grid-cols-3">{insights.map(item=><article key={item.title} className="flex flex-col bg-white p-7"><div className="text-[11px] font-bold uppercase tracking-[.2em] text-[#c85a24]">{item.cat}</div><div className="mt-3 text-xs font-semibold uppercase tracking-wider text-slate-400">From {item.source}</div><h2 className="mt-5 font-display text-2xl font-bold uppercase leading-tight">{item.title}</h2><div className="mt-6 border-l-2 border-[#c85a24] pl-4"><div className="text-[10px] font-bold uppercase tracking-[.2em] text-slate-400">Why we're reading it</div><p className="mt-3 text-sm leading-7 text-slate-600">{item.why}</p></div><a href={item.url} target="_blank" rel="noreferrer" className="mt-auto pt-7 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#c85a24]">Original source <ExternalLink className="h-4 w-4"/></a></article>)}</div></section>
  <section className="bg-[#1b232b] py-24 text-white"><div className="section-shell grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><div className="eyebrow">The Signal We're Watching</div><h2 className="mt-5 font-display text-4xl font-bold uppercase">The trades don't appear to have a demand problem. They may have a capacity problem.</h2></div><div className="space-y-5 text-lg leading-8 text-slate-400"><p>Meta and Associated Builders and Contractors launched a $115 million workforce initiative in 2026, beginning in Indiana and several other states, to prepare construction workers for data-center projects. The Wall Street Journal has separately reported major investments by employers and philanthropies into skilled-trades pipelines.</p><p>More work does not automatically create stronger companies. Opportunity can test workforce depth, leadership capacity, equipment, financial capacity, systems and operations simultaneously.</p><p className="font-semibold text-white">The winners may not simply be the companies capable of finding the most work. They may be the companies best prepared to carry it.</p><div className="flex flex-wrap gap-5 pt-2"><a href="https://www.abc.org/News-Media/News-Releases/meta-abc-form-partnership-to-launch-academy-to-train-and-create-jobs-for-construction-craft-professionals" target="_blank" rel="noreferrer" className="text-xs font-bold uppercase tracking-wider text-[#c85a24]">ABC source ↗</a><a href="https://www.wsj.com/business/autos/the-u-s-needs-mechanics-and-electricians-big-business-is-spending-to-create-some-7ea1f06c" target="_blank" rel="noreferrer" className="text-xs font-bold uppercase tracking-wider text-[#c85a24]">WSJ source ↗</a></div></div></div></section>
  <section className="bg-white py-20"><div className="section-shell text-center"><div className="eyebrow">Our Editorial Standard</div><h2 className="mt-5 font-display text-4xl font-bold uppercase">Curate. Contextualize. Connect.</h2><p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-slate-600">Third-party journalism remains clearly credited to the original publisher. Our role is to identify the signal, explain why we believe it matters, and connect it to the questions trade-business leaders should be considering.</p></div></section>
</main><Footer/></>}
